image: etna/drone-php7:php71
env:
  - APPLICATION_ENV=drone
  - COVERALLS_REPO_TOKEN=$$COVERALLS_TOKEN
  - COVERALLS_SERVICE_NAME=drone.io
script:
  - composer install --dev --no-interaction --prefer-source
  - composer phing
  - composer coveralls
notify:
  slack:
    team: {{slackTeam}}
    channel: {{slackChannel}}
    username: drone
    token: {{slackToken}}
    on_started: true
    on_failure: true
    on_success: true
